# Generated by Django 5.2.4 on 2026-04-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nombre_trottinettes', models.IntegerField(default=0)),
                ('duree_moyenne_location', models.FloatField(default=0)),
                ('distance_centre', models.FloatField(default=0)),
            ],
        ),
    ]
