# Generated by Django 5.2.4 on 2026-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='duree_moyenne_location',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='nombre_trottinettes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
