# Generated by Django 5.2.4 on 2026-03-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trottinette',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('QR_code', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('status', models.CharField(default='disponible', max_length=20)),
                ('battery', models.IntegerField(default=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discription', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('Trottinette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trottinette.trottinette')),
            ],
        ),
        migrations.CreateModel(
            name='TrottinetteBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.FloatField(default=0)),
                ('Trottinette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trottinette.trottinette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
