# Generated by Django 5.2.4 on 2026-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trottinette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trottinette',
            name='price_per_minute',
            field=models.FloatField(null=True),
        ),
    ]
