# Generated by Django 5.2.4 on 2026-04-21 08:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trottinette', '0003_trottinette_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trottinette',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='trottinette',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
