# Generated by Django 5.2.4 on 2026-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trottinette', '0004_trottinette_image_trottinette_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trottinettebooking',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmée', 'Confirmée'), ('refusée', 'Refusée'), ('terminée', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
