# Generated by Django 5.2.4 on 2026-04-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('trottinette', '0003_trottinette_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
        migrations.AddField(
            model_name='invoice',
            name='TrottinetteBooking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trottinette.trottinettebooking'),
        ),
    ]
